//
//  AMOSCDefine.h
//  AMOSCGroups
//
//  Created by wangwei on 7/1/15.
//  Copyright (c) 2015 王为. All rights reserved.
//

#ifndef AMOSCGroups_AMOSCDefine_h
#define AMOSCGroups_AMOSCDefine_h

#define AM_OSC_SRV_STARTED_NOTIFICATION @"AM_OSC_SRV_STARTED_NOTIFICATION"
#define AM_OSC_SRV_STOPPED_NOTIFICATION @"AM_OSC_SRV_STOPPED_NOTIFICATION"

#define AM_OSC_CLIENT_STARTED_NOTIFICATION @"AM_OSC_CLIENT_STARTED_NOTIFICATION"
#define AM_OSC_CLIENT_STOPPED_NOTIFICATION @"AM_OSC_CLIENT_STOPPED_NOTIFICATION"

#define AM_OSC_EVENT_TYPE   @"AM_OSC_EVENT_TYPE"
#define AM_OSC_NOTIFICATION @"AM_OSC_NOTIFICATION"
#define AM_OSC_TIMER_START @"/Artsmesh/Timer/Start"
#define AM_OSC_TIMER_STOP  @"/Artsmesh/Timer/Stop"


#endif
